# Copyright 2025 Chen Bainian
# Licensed under the Apache License, Version 2.0

try:
    from tomllib import load as toml_load
except ImportError:
    from tomli import load as toml_load

import os
import tomli_w
import sysconfig

import argparse
from pathlib import Path

from colcon_core.package_discovery import add_package_discovery_arguments
from colcon_core.plugin_system import satisfies_version
from colcon_core.verb import VerbExtensionPoint

from colcon_core.package_discovery import discover_packages
from colcon_core.package_identification \
    import get_package_identification_extensions
from colcon_python_project.package_identification.pep517 import PEP517PackageIdentification


_uv_venv_project_path = '.uv_python_project_venv'
_uv_venv_project_venv_subdirectory = '.venv'
_uv_venv_spec = 'pyproject.toml'
_uv_venv_python_version = '.python-version'

def get_uv_venv_path(install_base):
    """
    Get the base path for the uv project maintaining .venv.
    """
    path = None
    path = Path(str(install_base)) / Path(_uv_venv_project_path)

    if path == os.devnull:
        return None

    return Path(str(path))

def create_uv_venv_path(install_base):
    path = get_uv_venv_path(install_base)
    try:
        os.makedirs(str(path))
    except FileExistsError:
        pass  # Do nothing

    print(f"Using UV venv path '{path}'")


def get_python_projects(args):
    extensions = get_package_identification_extensions()
    descriptors = discover_packages(args, extensions)
    return descriptors

class VenvVerb(VerbExtensionPoint):
    """Edit a file within a package."""

    def __init__(self):  # noqa: D107
        super().__init__()
        satisfies_version(VerbExtensionPoint.EXTENSION_POINT_VERSION, '^1.0')

    def add_arguments(self, *, parser):  # noqa: D102
        add_package_discovery_arguments(parser)

        # only added so that package selection arguments can be used
        # which use the install directory to store .venv information
        parser.add_argument(
            '--install-base',
            default='install',
            help='The base path for all build directories (default: build)')

    def main(self, *, context):  # noqa: D102
        args = context.args
        descriptors = get_python_projects(args)
        venv_pkg_name = Path.cwd().name
        python_version = sysconfig.get_python_version()
        doc = {
            "project": {
                "name": venv_pkg_name,
                "version": "0.1.0",
                "description": "colcon uv venv management package",
                "requires-python": f'>={python_version}',
                "dependencies": []
            },
            "tool": {
                "uv": {
                    "sources": {}
                }
            }
        }
        doc_deps = doc["project"]["dependencies"]
        uv_sources = doc["tool"]["uv"]["sources"]
        for desc in descriptors:
            spec = desc.metadata.get('python_project_spec')
            if spec is None:
                continue

            build_backend = spec.get('build-system', {}).get('build-backend')

            # ignore setuptools legacy build
            if build_backend == 'setuptools.build_meta:__legacy__':
                continue

            # TODO(Briancbn): better validation
            doc_deps.append(desc.name)
            rel_path = Path('..') / Path('..') / desc.path
            uv_sources.update({ desc.name: {"path": str(rel_path)} })

        print(tomli_w.dumps(doc))
        create_uv_venv_path(args.install_base)
        spec_path = get_uv_venv_path(args.install_base) / _uv_venv_spec
        with open(spec_path, "wb") as f:
            f.write(b'# GENERATED BY COLCON VENV\n')
            tomli_w.dump(doc, f)

        python_version_path = get_uv_venv_path(args.install_base) / _uv_venv_python_version
        with open(python_version_path, "w") as f:
            f.write(python_version)
